name: Cypress testing

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.1'

      - name: Install dependencies
        run: |
          npm install

      - name: Build client
        run: |
          cd client
          npm install
          npm run build

      - name: Build server
        run: |
          cd server
          npm install
          npm run build

      - name: Run tests
        run: |
          npm run test-component
